### ISSUE TITLE
Add total counts

### ISSUE THREAD

**Issue by arthurTemporim** [brunohjs/rasa-model-report#73]
**Is there an existing idea for this?**
Please [search 🔍 the ideas](https://github.com/brunohjs/rasa-model-report/discussions/categories/ideas) to check if this idea has already been reported.
- [x] I have searched the existing ideas.

**Is your feature request related to a problem? Please describe.**
I have to count each `intent`, `intent example` etc to know the size of my chatbot.

**Describe the solution you'd like (optional)**
Have a total counter for `intents`, `stories`, `intent examples`, `stories usages`, etc. Have this at the end of each table would be a good solution for me.

**Describe alternatives you've considered (optional)**
I don't have.

**Futher Information (optional)**
I don't have.

**Comment by brunohjs** [comment]
Issuel solved on PR #77
